#checker.dgb:checker.dsf
#	dgasm.py checker.dsf -g 2U
	
#checker_trace.html:checker.dgb
#	dgsim.py checker.dgb -mn 5000
	
#html:checker_trace.html
#	xdg-open checker_trace.html

#clean:
#	rm *.dgb
#	rm *.html
#	rm *.hex

#simple_line.dgb:simple_line.dsf
#	dgasm.py simple_line.dsf -g 2U
	
#simple_line_trace.html:simple_line.dgb
#	dgsim.py simple_line.dgb -mn 5000
	
#html:simple_line_trace.html
##	xdg-open checker_trace.html

#clean:
#	rm *.dgb
#	rm *.html
#	rm *.hex

bbox.dgb:bbox.dsf
	dgasm.py bbox.dsf -g 2U
	
bbox_trace.html:bbox.dgb
	dgsim.py bbox.dgb -mn 5000
	
html:bbox_trace.html
#	xdg-open checker_trace.html

clean:
	rm *.dgb
	rm *.html
	rm *.hex
